import e from "express";
import upload from "../config/multer.js";
import { addFoodItem, getAllFoodItems, getItemById, removeItemById } from "../controllers/food.controller.js";
import auth from "../middlewares/auth.js";
const FoodRouter=e.Router();
FoodRouter.post("/add",upload.single("image"),auth,addFoodItem);
FoodRouter.get("/all",getAllFoodItems);
FoodRouter.get("/:id",getItemById);
FoodRouter.post("/delete",removeItemById);
export default FoodRouter;